import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import ClientLayout from "./ClientLayout"; // <== client component

export const metadata = {
  title: "SMART Marketplace",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <StoreProvider>
            <ClientLayout>
              {children}
            </ClientLayout>
          </StoreProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}